- name: Install RedHat Apache Web Server
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD RedHat
- name: Install Debian Apache Web Server
  apt: pkg={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian'"
  notify: Restart HTTPD Debian
