--- # Local playbook example
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Get network configuration
      command: /usr/bin/ifconfig
      register: net_cfg
    - debug: var=net_cfg
    - name: Install htop
      pacman: name=htop state=latest