--- # Lookup playbook example.
- hosts: apacheweb
  user: test
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    # - debug: msg="Lookup superhero for Bruce Wayne {{ lookup('csvfile', 'Wayne file=lookup.csv delimiter=, default=NOMATCH') }}"
    - debug: msg="{{ lookup('env', 'HOME') }} is the value of the $HOME env variable."