--- # PROMPT playbook example
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_prompt:
    - name: pkginstall
      prompt: Install which package?
      default: telnet
      private: no
  tasks:
    - name: Install the {{ pkginstall }} package.
      yum: name={{ pkginstall }} state=latest