--- # Tag functionality example
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet and lynx
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verify that telnet was installed
      raw: yum list installed | grep telnet > /home/test/pkg.log
      tags:
        - verification