--- # My First YAML playbook for Ansible.
- hosts: all
  user: test
  become: true
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: What package do you want to install?
  tasks:
    - name: Install the apache web server
      yum: pkg=httpd state=latest
      async: 300
      poll: 3
      notify: start httpd

    - name: Install the {{ pkg_name }} package
      yum: pkg={{ pkg_name }} state=latest
  handlers:
    - name: "start httpd"
      service: name=httpd state=restarted