--- # Build an Apache webserver

- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    apache_pkg: httpd
    distribution: redhat
    apache_version: 2.4
    apache_dir: /var/www/sample
    apache_fqdn: mpalade2.mylabserver.com

  tasks:
    - name: Install the Web Server
      yum: pkg={{ apache_pkg }} state=latest
    - name: Create the web server directory
      file: path={{ apache_dir }} state=directory mode=644
    - name: Copy the Apache configuration file to the remote host
      copy: src=files/httpd.conf.template dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=644
    - name: Create the VHOST.D directory on the remote host
      file: path=/etc/httpd/vhost.d state=directory mode=755
    - name: Copy and untar the source for the site
      unarchive: src=files/sitecode.tar.gz dest={{ apache_dir }}
    - name: Copy the default Vhost configuration file
      copy: src=files/default.conf.template dest=/etc/httpd/vhost.d/default.conf owner=root group=root mode=644
    - name: Start the web server
      service: name={{ apache_pkg }} state=started
    - name: Test the web server
      shell: curl {{ apache_fqdn }}
      register: result
    - name: Display the result
      debug: var=result