--- # Master playbook for NFS Server deployments.
- hosts: appserver
  user: test
  become: yes
  connection: ssh
  gather_facts: yes
  pre_tasks:
    - name: ROLE start
      raw: date > /home/test/role-start.log
  roles:
    - nfs.server
  post_tasks:
    - name: ROLE end
      raw: date > /home/test/role-end.log
