--- # Master playbook for the redhat web server role.
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: yes
  pre_tasks:
    - name: ROLE start
      raw: date > /home/test/role-start.log
  roles:
    - redhat.apachewebserver
  post_tasks:
    - name: ROLE end
      raw: date > /home/test/role-end.log
