--- # J2 template module example
- hosts: apacheweb, debian
  user: test
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    userName: test
    userPassword: password1234
    connectionType: SFTP

  tasks:
    - name: Install the configuration file customized for the system.
      template:
        src: test.conf.j2
        dest: /home/test/test.conf
        owner: test
        group: test
        mode: 0750
