- name: Install RedHat Apache Web Server
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  # notify: Restart HTTPD RedHat
- shell: systemctl status httpd
  register: result
  until: result.stdout.find('active (running)') != -1
  retries: 5
  delay: 5
- debug: var=result
# - name: Wait for HTTPD to be started
#   wait_for:
#     port: 80
#     state: started
