- name: InstallClientPackages
  yum: pkg={{ item }} state=latest
  with_items:
    - "{{ nfsutils_pkg }}"
    - "{{ nfsutilslib_pkg }}"
  notify: StartClientServices
- name: StartClientServices
  service: name={{ item }} state=restarted
  with_items:
    - "{{ nfslock_service }}"
    - "{{ nfsmap_service }}"
    - "{{ rpcbind_service }}"
- name: CreateClientMount
  file: path={{ client_path }} state=directory mode=755
- name: ClientMountServerResource
  shell: mount -t nfs mpalade3.mylabserver.com:{{ export_path }} {{ client_path }}
  register: result
- name: TestServerAvailability
  debug: var=result